### PR TITLE
Fix issue with Chrome 67+

### PR DESCRIPTION
**Pull request by dheerajkumarmadaan**
…D_INPUT anymore. Refactored code to pass empty object if ALLOW_KEYBOARD_INPUT is not found.

### CODE REVIEW

**Comment by sindresorhus** [comment]
`document.body.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)` works fine, so I'm not sure what the issue actually is?

**Comment by dheerajkumarmadaan** [comment]
screen shot 2018-08-27 at 1 50 38 pm

I tried demo page on chrome 68 and found this error.   It is reproducible on multiple system, I can see it is working on some other chrome 68 as well. Not sure what 's the special settings that you need to turn on your chrome to reproduce this.

Assume you cannot reproduce this but below line is still buggy:

elem[request](keyboardAllowed && Element.ALLOW_KEYBOARD_INPUT);
Let say keyboardAllowed is false so this method would be invoked with:
elem[request](false)
i.r webkitRequestFullScreen(false)

But this method takes object as an argument and it will throw error as specified in screen shot.
This PR will handle this case.

**Comment by dheerajkumarmadaan** [comment]
screen shot 2018-08-27 at 1 58 06 pm

**Comment by sindresorhus** [comment]
I cannot reproduce this on either 68.0.3440.106 or 70.0.3534.0 on macOS. Which exact Chrome version are you on? It might have been fixed in a minor v68 version.

**Comment by sindresorhus** [comment]
I don't like changing something I cannot reproduce, but alright. Please remove the `dist` content. This will be generated on release.

**Comment by dheerajkumarmadaan** [comment]
Ok.. Removed dist folder changes for screenfull.js

**Comment by sindresorhus** [comment]
There's still a diff for `dist/screenfull.min.js`

**Comment by amccloud** [comment]
@dheerajkumarmadaan @sindresorhus I’m able to reproduce with the same browser/os

Adding error text to this issue so other people can search for it. 

```
TypeError
Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
```

**Comment by salilk** [comment]
@dheerajkumarmadaan @sindresorhus @amccloud -- I’m also able to reproduce the issue. Looking at the PR - the fix looks good as well as safe. Thanks!!

**Comment by dheerajkumarmadaan** [comment]
@sindresorhus  I just removed dis changes.

**Comment by shuodashen** [comment]
I can reproduce this issue on Chrome Canary, which version is : 72.0.3616.0 (Official Build) canary (64-bit).
Since this commit is merged,  I will upgrade to the latest version and try again.

**Comment by joedf** [comment]
Updating to from v3.3.2 - 2017-10-27 to v4.1.0 - 2019-03-19 worked for me! 👍

**Pull request merged**
