### PR TITLE
Add support for options

### LINKED ISSUE #114: Support `requestFullscreen()` options
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/screenfull.js/issues/114)

See https://developer.mozilla.org/en-US/docs/Web/API/FullscreenOptions

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#148 Add FullscreenOptions to request](https://issuehunt.io/r/sindresorhus/screenfull.js/pull/148)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/screenfull.js/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by silltho**
I needed the support of the FullscreenOptions to hide the navbar on mobile devices. Since the PR #148 related to the issue was closed I wanted to share this with you.

resolves #114

### CODE REVIEW

**Comment by silltho** [comment]
summoning @sindresorhus 😄

**Comment by sindresorhus** [comment]
You need to add it to the readme too.

**Comment by silltho** [comment]
Good point. I updated the api documentation and added an example how to hide navigation ui on mobile devices.

**Comment by sindresorhus** [comment]
You need to update the `.toggle()` docs in the readme too.

**Pull request merged**
